FROM mariadb:latest

COPY ./banco/99privileges.sql /docker-entrypoint-initdb.d/
COPY ./banco/schemaradius.sql /docker-entrypoint-initdb.d/

RUN chown -R mysql:mysql /docker-entrypoint-initdb.d/
RUN chmod -R +0777 /docker-entrypoint-initdb.d/